services:
  - type: web
    name: paribus-bulk-processing-system
    env: python
    buildCommand: uv sync --extra dev
    startCommand: uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: HOSPITAL_DIRECTORY_API_BASE_URL
        value: https://hospital-directory.onrender.com
      - key: MAX_CSV_HOSPITALS
        value: "20"
